# Generated by Django 5.2.1 on 2025-05-23 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("splits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="split",
            name="split_name",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(limit_value=1)],
                verbose_name="split_name",
            ),
        ),
    ]
