# Generated by Django 5.2.1 on 2025-05-21 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="choice_text",
            field=models.CharField(
                max_length=200,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(limit_value=5)],
                verbose_name="choice_text",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="question_text"
            ),
        ),
    ]
