# Generated by Django 5.2.1 on 2025-05-21 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_choice_choice_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="choice_text",
            field=models.CharField(
                max_length=200,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(limit_value=1)],
                verbose_name="choice_text",
            ),
        ),
    ]
